version: '1'

stages:
  - name: ZAP DAST Scan

    jobs:
      - name: Run-ZAP

        type: builder

        image: ghcr.io/zaproxy/zaproxy:stable

        script: |
          #!/bin/bash
          set -euxo pipefail

          chmod +x scripts/run-zap.sh

          ./scripts/run-zap.sh

          mkdir -p artifacts

          cp /zap/wrk/reports/zap-report.html artifacts/

          echo "Artifact contents:"
          ls -lah artifacts/

        artifacts:
          paths:
            - artifacts/zap-report.html
